# Generated by Django 3.1.2 on 2020-10-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.IntegerField()),
                ('chat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='songs.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('mark', models.IntegerField()),
                ('poll_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.poll')),
            ],
        ),
    ]
